- name: play level variables
  hosts: localhost
  vars:
    gname: "pavani"
  tasks:
    - name: display variables
      vars:
        gname: "naidu"
      ansible.builtin.debug:
        msg: "{{ gname }}"
