- name: play level variables
  hosts: localhost
  var_files:
  - call_files.yml
  tasks:
    - name: display variables
      ansible.builtin.debug:
        msg: "{{course}} ---{{dureation}}---{{trainer}}"