- name: prioritize variables
  hosts: localhost
  vars:
    course: "devops" #3
  vars_files:
  - vars.yml #4
  vars_prompt:
    - name: course
      prompt: "Please enter course"

  tasks:
    - name: task level variables #2
#      vars:
#        course: "angular"
      ansible.builtin.debug:
        msg: "{{course}}"

#1.cmd line args
#2.tasks level